# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.4.10, 2.5.9, 2.6.10, 2.7.6]
        activemodel: [5.1.x, 5.2.x, 6.0.x, 6.1.x, 7.0.x]
        exclude:
          - ruby-version: 2.4.10
            activemodel: 6.0.x
          - ruby-version: 2.4.10
            activemodel: 6.1.x
          - ruby-version: 2.4.10
            activemodel: 7.0.x
          - ruby-version: 2.5.9
            activemodel: 7.0.x
          - ruby-version: 2.6.10
            activemodel: 7.0.x

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install --gemfile gemfiles/Gemfile.activemodel-${{ matrix.activemodel }}
    - name: Run tests
      run: bundle exec rake spec
